language: c
compiler:
    - gcc
    - clang
before_script:
    - sudo apt-get install apache2 apache2-prefork-dev
    - wget http://squirrel.googlecode.com/files/squirrel_3_0_4_stable.tar.gz
    - tar xzvf squirrel_3_0_4_stable.tar.gz
    - wget https://raw.github.com/njlg/gentoo-overlay/master/dev-lang/squirrel/files/squirrel-3.0.4-autotools.patch
    - patch -p0 < squirrel-3.0.4-autotools.patch
    - cd SQUIRREL3
    - mkdir m4
    - autoreconf -vfi
    - ./configure
    - make && sudo make install
    - cd ..
    - autoreconf -vfi
script: ./configure && make && sudo make install
after_script:
    - echo "$(curl -fsSL https://gist.github.com/raw/4545449/90f425ea144f9d23464d470f005c62bafc975d5e/gistfile1.apacheconf)" | sed -e "s,PATH,`pwd`/examples,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
    - sudo service apache2 restart
    - curl http://localhost/welcome.nut
    - curl http://localhost/globals.nut
    - curl http://localhost/file.nut
    - curl http://localhost/header.nut
    - cat /var/log/apache2/error_log
